name: Release current main branch.
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mduessler/fedora-nvim:unit-test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_PAT }}
    steps:
      - name: Prepare Release.
        run: |
          git clone https://github.com/mduessler/nvim-config ${NVIM_CONFIG}
          cd ${NVIM_CONFIG}
          source ./dependencies
          export NVIM_VERSION="v.${NVIM_MAJOR_REQ}.${NVIM_MINOR_REQ}.${NVIM_PATCH_REQ}"
          git checkout main
          git config user.name "github-release-bot[${{ github.actor }}]"
          git config user.email "github-release-bot@noreply.github.com"
      - name: Select files from main to release.
        run: |
          git checkout -b "${NVIM_VERSION}" -- \
            installs \
            lua \
            .gitignore \
            dependencies \
            init.lua \
            install \
            lazy-lock.json \
            LICENSE \
            README.md
      - name: Remove development section from README.md
        run: sed -i '/^## Development/,/^## Notes & Feedback/ {/^## Notes & Feedback/!d}' README.md
      - name: Create release for nvim version.
        run: |
          git add \
            installs \
            lua \
            .gitignore \
            dependencies \
            init.lua \
            install \
            lazy-lock.json \
            LICENSE \
            README.md
          git commit -m "Release for nvim ${NVIM_VERSION}"
          git tag -a ${NVIM_VERSION} -m "Release for nvim ${NVIM_VERSION}"
          git push origin --tags
