name: Release current main branch.
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mduessler/fedora-nvim:unit-test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_PAT }}
    steps:
      - name: Prepare Release.
        run: |
          git clone https://github.com/mduessler/nvim-config ${NVIM_CONFIG}
          cd ${NVIM_CONFIG}
          if git rev-parse "v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ}" >/dev/null 2>&1; then
            echo "Tag v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ} already exists. Stopping release." && exit 1
          fi
          git checkout main
          export USERNAME="${{ github.actor }}"
          export TOKEN="${{ secrets.PACKAGES_PAT }}"
          git config user.name "github-release-bot[${{ github.actor }}]"
          git config user.email "github-release-bot@noreply.github.com"
      - name: Select files from main to release.
        run: |
          cd ${NVIM_CONFIG}
          git checkout --orphan "v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ}"
          git rm -rf .
          ls -l
          git status
          git checkout main -- \
            installs \
            lua \
            .gitignore \
            dependencies \
            init.lua \
            install \
            lazy-lock.json \
            LICENSE \
            README.md
          ls -l
          git status
      - name: Remove development section from README.md
        run: |
          cd ${NVIM_CONFIG}
          sed -i '/^## Development/,/^## Notes & Feedback/ {/^## Notes & Feedback/!d}' README.md
      - name: Create release for nvim version.
        run: |
          cd ${NVIM_CONFIG}
          git add \
            installs \
            lua \
            .gitignore \
            dependencies \
            init.lua \
            install \
            lazy-lock.json \
            LICENSE \
            README.md
          git commit -m "Release for nvim v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ}"
          git tag -a "v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ}" -m "Release for nvim v${MAJOR_REQ}.${MINOR_REQ}.${PATCH_REQ}"
          git tag -f latest
          git push https://${USERNAME}:${TOKEN}@github.com/${{ github.repository }} HEAD --tags
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.PACKAGES_PAT }}
